14 lesson api
Runidan/TestGuru pull request #16
Opened 2022-11-19 14:48 UTC by Runidan

2022-11-20 06:49 UTC, VidgarVii requested changes

2022-11-20 06:49 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    flash_options = if @result.nil?
Метод call для сервисов по соглашению возвращает какой-то результат. Тут всё верно. Но результат он есть всегда, какой бы он не был. Тут скорей надо проверять успешность выполнения сервиса.
Для этого принято использовать метод `success?` Т.е. мы проверяем успешно ли сервис создал Гист

2022-11-20 06:49 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
установка "нил" в аргументах - это возможно не лучшее решение
я бы для такого случая порекомендовал вариант установки дефолта, к примеру, такой:
```ruby
def initialize(question, client = default_client)
  ...
  @client = client
end
```
далее можно определить в методе `default_client` "дефолтного клиента"

```ruby
private

def default_client
  Octokit::Client.new(access_token: GITHUB_GIST_TOKEN)
end
```

2022-11-20 06:49 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client = client || Octokit::Client.new(access_token: ENV['GITHUB_API'])
если токена не будет. то ошибка будет на стороне октокит. Что не совсем корректно. Лучше проверку токена делать явной. Для этого можно воспользоваться  fetch
ENV.fetch('GITHUB_API')

2022-11-20 06:49 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +                      { notice: t('.success', gist_url: @result.url) }
в сервисе нет метода url

2022-11-20 06:49 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client.create_gist(gist_params)
Метод call должен вернуть такой объект, который содержит все нужные методы и данные. И хорошо если всё это будет прописано в явном виде. Сейчас же не понятно от куда берутся методы такие как html_url. 
Для создания такого объекта можно воспользоваться Struct 
Минус твоего подхода в том, что если придётся менять гем, то придётся исправлять код в разных местах проекта. А класс GistQuestionService служит своего рода адаптером над октокит. Его задача не только создавать гист. Это он вообще делегирует гему октокит. А скрыть сложность создания гиста и предоставить общий интерфейс, который не зависит от хттп клиента. И если придётся менять этот хттп клиент, то рефакторигну подвергнется только сервис  GistQuestionService

2022-11-20 06:49 UTC, VidgarVii commented on config/locales/ru.yml
> +      success: "Гист успешно создан по адресу: %{gist_url}"
ссылка должна быть кликабельной

2022-11-21 04:56 UTC, Runidan commented on app/services/gist_question_service.rb
> +    @client = client || Octokit::Client.new(access_token: ENV['GITHUB_API'])
done

2022-11-21 04:56 UTC, Runidan commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
done

2022-11-21 05:53 UTC, Runidan commented on config/locales/ru.yml
> +      success: "Гист успешно создан по адресу: %{gist_url}"
done

2022-11-23 05:27 UTC, merged