Lesson4  active record query interface
Runidan/TestGuru pull request #6
Opened 2022-05-18 05:55 UTC by Runidan

2022-05-18 16:22 UTC, VidgarVii requested changes

2022-05-18 16:22 UTC, VidgarVii commented on Gemfile
> +gem 'net-smtp', '0.3.1'
зачем нужен этот гем? Его даже не будем использовать

2022-05-18 16:22 UTC, VidgarVii commented on app/models/test.rb
> +    category_id = Category.select(:id).where("title = :title", title:category).first
переменная названа не верно. Она не содержит category id

2022-05-18 16:22 UTC, VidgarVii commented on app/models/test.rb
> +    category_id = Category.select(:id).where("title = :title", title:category).first
не забывай разделять слова пробелами.
Неоченьприятночитатьтакойтекст,правда?

2022-05-18 16:22 UTC, VidgarVii commented on app/models/test.rb
> +  end
здесь будет два отдельных запроса к базе, это не очень оптимально
несложно записать все в один запрос использую JOIN. Запомни простое правило. Если надо что-то получить из БД. То 100% делегируй задачу базе. Пусть данными агрегирует база. Для этого и был создан SQL. А ОРМ тебе поможет написать запрос проще и безопасней

2022-05-18 16:22 UTC, VidgarVii commented on app/models/test.rb
> +  end
По заданию нужен массив тестов, у тебя сейчас возвращается ActiveRecord::Relation

2022-05-18 16:22 UTC, VidgarVii commented on app/models/test.rb
> +  def self.titles(category)
Не удачное название для параметра метода. По названию параметра метода можно понять что надо передать сам объект категории. А по факту надо передать название категории.

2022-05-18 16:22 UTC, VidgarVii commented on app/models/test.rb
> +  def self.titles(category)
по названию метода можно понять, что он просто возвращает titles тестов. Надо давать более развёрнутые названия, чтобы было понято, что делает метод или возвращает

2022-05-18 16:22 UTC, VidgarVii commented on app/models/user.rb
> +  end
лучше всего, где это возможно, использовать "хеш-синтаксис" (см. выше ^^) - обычно это лаконичней и легче править
`were(level: level)`

2022-05-18 16:22 UTC, VidgarVii commented on app/models/test.rb
> +    Test.where(category_id:category_id).order(title: :asc).select(:title)
писать Test нет ни какого смысла и лучше так не делать. Так как это метод класса, метод where и так будет вызван у объекта Test
А сейчас получается так как будто обращаясь к человеку называем его имя 2 раза

2022-05-18 16:22 UTC, VidgarVii commented on db/seeds.rb
> +users = User.create([
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2022-05-18 16:22 UTC, VidgarVii commented on db/seeds.rb
> +  category_id: Category.find_by(title: 'Логика').id,
посмотри пример на 5,6 строке.
Эти лишние запросы в базу только замедлят работу и они тут совсем не нужны. Используй то что возвращает метод create

2022-05-18 16:22 UTC, VidgarVii commented on db/seeds.rb
> +])
No new lina at end of file

2022-05-19 06:28 UTC, Runidan commented on Gemfile
> +gem 'net-smtp', '0.3.1'
Удалил.

2022-05-19 06:55 UTC, Runidan commented on Gemfile
> +gem 'net-smtp', '0.3.1'
Устанавливал по причине, что терминал ругался на его отсутствие при запуске консоли раилс:
You don't have net-smtp installed in your application. Please add it to your Gemfile and run bundle install
Running via Spring preloader in process 977
Loading development environment (Rails 6.1.6)
3.1.1 :001 >

2022-05-19 08:08 UTC, Runidan commented on db/seeds.rb
> +  category_id: Category.find_by(title: 'Логика').id,
Тут не могу понять задачу. В примере movies.first разве не является таким же запросом к базе?  Если только убрать отдельное предварительное создание категории и добавлять ее при создании теста, а из того, что возвращается извлекать id.

2022-05-20 06:31 UTC, VidgarVii requested changes

2022-05-20 06:31 UTC, VidgarVii commented on db/seeds.rb
> +  author_id: User.find_by(login: 'Cozy').id
1 не исправил. Все нужные данные у тебя уже есть в памяти. Все созданные юзеры находятся в переменной users. Используй переменную, а не запросы в базу
2 не вижу чтобы тут создавались категории. Получается сдаёшь на проверку не рабочий код(

2022-05-20 06:31 UTC, VidgarVii commented on db/seeds.rb
> +
это лишний отступ

2022-05-20 06:31 UTC, VidgarVii commented on db/seeds.rb
> +)
https://github.com/Runidan/TestGuru/pull/6#discussion_r876099562

2022-05-20 06:31 UTC, VidgarVii commented on app/models/test.rb
> +    Test
можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2022-05-20 09:04 UTC, Runidan commented on db/seeds.rb
> +  author_id: User.find_by(login: 'Cozy').id
2. Категории создаются методом find_or_create_by!, если не были созданы ранее. Код запускал, данные таблицу успешно добавлялись.

2022-05-22 07:24 UTC, merged